Added error handle for 401 Error, allow redirect to login auth url
trypear/pearai-submodule pull request #109
Opened 2024-07-21 14:28 UTC by Pockylee

## Description

As the title, however, I currently haven't found a method to reproduce the error. As a result, we might have to merge and then test in prod.

## Add

Add a third option when the user faces the 401 Error, allow redirect to login #195 issue in pearai-app

2024-07-21 14:36 UTC, Pockylee commented
[Link to issue](https://github.com/trypear/pearai-app/issues/195)

2024-07-21 17:56 UTC, Ellahinator commented on extensions/vscode/src/webviewProtocol.ts
> +                      'https://trypear.ai/signin?...llback=pearai://pearai.pearai/auth',
typo
```suggestion
                      'https://trypear.ai/signin?callback=pearai://pearai.pearai/auth',
```

2024-07-21 18:06 UTC, Pockylee commented on extensions/vscode/src/webviewProtocol.ts
> +                      'https://trypear.ai/signin?...llback=pearai://pearai.pearai/auth',
Fixed, tysm

2024-07-23 16:03 UTC, nang-dev commented
F on test on prod, nw ill watch it with you

2024-07-30 17:34 UTC, siddharthjha387 requested changes

2024-07-30 17:34 UTC, siddharthjha387 commented on extensions/vscode/src/webviewProtocol.ts
> +          if (e.status === 401) {
Do not use magic number, use constant for '401'. Check at other places also

2024-07-30 17:34 UTC, siddharthjha387 commented on extensions/vscode/src/webviewProtocol.ts
> +              });
Can we wrap this logic inside function?

2024-08-02 02:44 UTC, nang-dev commented
imma test this :D

2024-08-02 05:04 UTC, nang-dev commented
Added polish and merged!

2024-08-02 05:04 UTC, nang-dev approved these changes

2024-08-02 05:04 UTC, merged

2024-08-02 09:58 UTC, Pockylee commented
Thanks for the help!!!