Removed hard coded supabase keys
trypear/pearai-submodule pull request #155
Opened 2024-08-22 22:11 UTC by MaxFSP

## Description ✏️

Closes   Remove hard coded supabase keys in submodule ( issue #149 on trypear/pearai-server ) 

What changed? Feel free to be brief.

Eliminated the need for hard coding of the url and keys, and added function to call them from the server

## Checklist ✅

- [ ] I have added screenshots (if UI changes are present).
- [ ] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).

2024-08-23 23:20 UTC, nang-dev requested changes
we need it to keep lines 4+5

2024-08-23 23:20 UTC, nang-dev commented on core/db/token.ts
> +    const supabaseTokens = await requestTokens(accessToken);
okay this shouldnt be in check tokens, the request tokens should be on line 28 i think

and then i dont see create client in the original

2024-08-24 21:13 UTC, MaxFSP commented on core/db/token.ts
> +  await initializeSupabase();
it does run, but if supabase is already initiated then it skips the request

2024-08-24 21:15 UTC, MaxFSP commented on core/db/token.ts
> +  await initializeSupabase();
it basically just acts like another if statement and if its true then it just continues and doesnt request anything to the server

2024-08-25 15:26 UTC, nang-dev commented
NICE

2024-08-25 15:26 UTC, merged